export const packagesData = [
  // Gulmarg Packages
  {
    title: "Gulmarg Skiing Adventure",
    image: "/images/packages/skiing.jpg",
    location: "Gulmarg",
    duration: "4 days",
    people: "Per Person",
    price: "₹14,999",
  },
  {
    title: "Gulmarg Gondola Ride",
    image: "/images/packages/gondola.jpg",
    location: "Gulmarg",
    duration: "3 days",
    people: "Per Person",
    price: "₹9,999",
  },
  {
    title: "Gulmarg Snowboarding Tour",
    image: "/images/packages/snowboarding.jpg",
    location: "Gulmarg",
    duration: "5 days",
    people: "Per Person",
    price: "₹16,500",
  },
  {
    title: "Gulmarg Winter Wonderland",
    image: "/images/packages/snow_mountain.jpg",
    location: "Gulmarg",
    duration: "3 days",
    people: "Per Person",
    price: "₹12,999",
  },
  {
    title: "Gulmarg Golf Retreat",
    image: "/images/packages/gulmarg_golf.jpg",
    location: "Gulmarg",
    duration: "4 days",
    people: "Per Person",
    price: "₹14,000",
  },

  // Pahalgam Packages
  {
    title: "Pahalgam River Rafting",
    image: "/images/packages/pahalgam_rafting.jpg",
    location: "Pahalgam",
    duration: "3 days",
    people: "Per Person",
    price: "₹12,500",
  },
  {
    title: "Pahalgam Aru Valley Trek",
    image: "/images/packages/pahalgam.jpg",
    location: "Pahalgam",
    duration: "4 days",
    people: "Per Person",
    price: "₹14,000",
  },
  {
    title: "Pahalgam Betaab Valley Tour",
    image: "/images/packages/green_medows.jpg",
    location: "Pahalgam",
    duration: "2 days",
    people: "Per Person",
    price: "₹8,500",
  },

  // Sonamarg Packages
  {
    title: "Sonamarg Thajiwas Glacier Trek",
    image: "/images/packages/sonamarg.jpg",
    location: "Sonamarg",
    duration: "3 days",
    people: "Per Person",
    price: "₹13,999",
  },
  {
    title: "Sonamarg Camping Adventure",
    image: "/images/packages/sonamarg_camping.jpg",
    location: "Sonamarg",
    duration: "4 days",
    people: "Per Person",
    price: "₹15,500",
  },
  {
    title: "Sonamarg Zoji La Pass Trip",
    image: "/images/packages/sonamarg_zojila.jpg",
    location: "Sonamarg",
    duration: "2 days",
    people: "Per Person",
    price: "₹10,000",
  },
  // General Kashmir Packages
  {
    title: "Kashmir Honeymoon Special",
    image: "/images/packages/kashmir-honeymoon.jpg",
    location: "Kashmir",
    duration: "5 days",
    people: "Per Person",
    price: "₹25,000",
  },
  {
    title: "Kashmir Heritage Tour",
    image: "/images/packages/kashmir_heritage.jpg",
    location: "Kashmir",
    duration: "5 days",
    people: "Per Person",
    price: "₹18,000",
  },
  {
    title: "Kashmir Wildlife Safari",
    image: "/images/packages/forest.jpg",
    location: "Kashmir",
    duration: "6 days",
    people: "Per Person",
    price: "₹20,000",
  },
  {
    title: "Kashmir Family Vacation",
    image: "/images/packages/kashmir_family.jpg",
    location: "Kashmir",
    duration: "7 days",
    people: "Per Person",
    price: "₹22,000",
  },
  {
    title: "Kashmir Adventure Package",
    image: "/images/packages/kashmir_adventure.jpg",
    location: "Kashmir",
    duration: "6 days",
    people: "Per Person",
    price: "₹27,000",
  },

  // Srinagar Packages
  {
    title: "Srinagar Houseboat Experience",
    image: "/images/packages/houseboat.jpg",
    location: "Srinagar",
    duration: "3 days",
    people: "Per Person",
    price: "₹9,999",
  },
  {
    title: "Srinagar Mughal Gardens Tour",
    image: "/images/packages/srinagar_gardens.jpg",
    location: "Srinagar",
    duration: "2 days",
    people: "Per Person",
    price: "₹7,500",
  },
  {
    title: "Srinagar Cultural Delight",
    image: "/images/packages/srinagar_culture.jpg",
    location: "Srinagar",
    duration: "4 days",
    people: "Per Person",
    price: "₹12,000",
  },
  {
    title: "Srinagar and Gulmarg Combo",
    image: "/images/packages/srinagar_gulmarg.jpg",
    location: "Srinagar, Gulmarg",
    duration: "5 days",
    people: "Per Person",
    price: "₹15,000",
  },
  {
    title: "Srinagar Leisure Package",
    image: "/images/packages/srinagar_leisure.jpg",
    location: "Srinagar",
    duration: "3 days",
    people: "Per Person",
    price: "₹8,500",
  },

  // Leh-Ladakh Packages
  {
    title: "Leh-Ladakh Bike Expedition",
    image: "/images/packages/ladakh-ride.jpg",
    location: "Leh-Ladakh",
    duration: "10 days",
    people: "Per Person",
    price: "₹28,999",
  },
  {
    title: "Leh-Ladakh Cultural Tour",
    image: "/images/packages/leh_cultural_tour.jpg",
    location: "Leh-Ladakh",
    duration: "7 days",
    people: "Per Person",
    price: "₹26,500",
  },
  {
    title: "Leh-Ladakh Photography Tour",
    image: "/images/packages/leh_photography_tour.jpg",
    location: "Leh-Ladakh",
    duration: "8 days",
    people: "Per Person",
    price: "₹30,000",
  },
  {
    title: "Leh-Ladakh Jeep Safari",
    image: "/images/packages/leh_jeep_safari.jpg",
    location: "Leh-Ladakh",
    duration: "9 days",
    people: "Per Person",
    price: "₹32,000",
  },
];
