export const packagesData = [
  {
    title: "Luxury Beach Tour",
    image: "/images/home/gulmarg.jpg",
    location: "Thailand",
    duration: "3 days",
    people: "2 Person",
    price: "14999",
  },
  {
    title: "Mountain Adventure",
    image: "/images/home/gulmarg.jpg",
    location: "Switzerland",
    duration: "5 days",
    people: "4 Person",
    price: "29999",
  },
  {
    title: "Desert Safari",
    image: "/images/home/gulmarg.jpg",
    location: "Dubai",
    duration: "2 days",
    people: "3 Person",
    price: "11199",
  },
  {
    title: "Cultural Trip",
    image: "/images/home/gulmarg.jpg",
    location: "Italy",
    duration: "6 days",
    people: "2 Person",
    price: "13999",
  },
  {
    title: "Jungle Expedition",
    image: "/images/home/gulmarg.jpg",
    location: "Amazon",
    duration: "7 days",
    people: "5 Person",
    price: "20000",
  },
  {
    title: "Northern Lights Experience",
    image: "/images/home/gulmarg.jpg",
    location: "Norway",
    duration: "4 days",
    people: "2 Person",
    price: "14449",
  },
];
