export const packagesData = [
  {
    title: "Luxury Beach Tour",
    image: "/images/home/gulmarg.jpg",
    location: "Thailand",
    duration: "3 days",
    people: "2 Person",
    price: "149.00",
  },
  {
    title: "Mountain Adventure",
    image: "/images/home/gulmarg.jpg",
    location: "Switzerland",
    duration: "5 days",
    people: "4 Person",
    price: "299.00",
  },
  {
    title: "Desert Safari",
    image: "/images/home/gulmarg.jpg",
    location: "Dubai",
    duration: "2 days",
    people: "3 Person",
    price: "199.00",
  },
  {
    title: "Cultural Trip",
    image: "/images/home/gulmarg.jpg",
    location: "Italy",
    duration: "6 days",
    people: "2 Person",
    price: "399.00",
  },
  {
    title: "Jungle Expedition",
    image: "/images/home/gulmarg.jpg",
    location: "Amazon",
    duration: "7 days",
    people: "5 Person",
    price: "349.00",
  },
  {
    title: "Northern Lights Experience",
    image: "/images/home/gulmarg.jpg",
    location: "Norway",
    duration: "4 days",
    people: "2 Person",
    price: "449.00",
  },
];
